//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.28 at 02:23:11 PM CDT 
//


package gameObjects;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextPane;
import javax.swing.tree.DefaultMutableTreeNode;

import coreGame.Game;
import gameData.ActionData;
import gameData.ChoiceData;

public class Choice
    extends Action
{

	public Choice(ChoiceData data){
	this.actionData = data;
	data.setLinkedGameObject(this);
	}
	
    @Override
	public ChoiceData getActionData(){
		return (ChoiceData) actionData;	
	}
	
    @Override
	public String toString() {
    	if(this.getActionData().getNAME() == null){
    		return "Choice: " + this.getActionData().getKeyword().get(0);
    	}
		return "Choice: " + this.getActionData().getNAME();
	}

    public DefaultMutableTreeNode getNode(){
		DefaultMutableTreeNode node = new DefaultMutableTreeNode(this);
		for (ActionData actionData : this.getActionData().getTransitionOrPythonScriptOrChoice()){
			node.add(actionData.getLinkedGameObject().getNode());
		}
	return node;
	}

    
    
    public void run() {
    	for(String s :this.getActionData().getKeyword() ) {
    	Game.currentGame.gameWindow.addChoice(s,this.getActionData().getTransitionOrPythonScriptOrChoice(), this.getActionData().isHidden() );
        
    	}
        }
    /**
     * @wbp.parser.entryPoint
     */
    @Override
    public void addEditorPannel(JPanel panel) {
		super.addEditorPannel(panel);
		JPanel panel_1 = new JPanel();
    	panel.add(panel_1);
	}


}
