//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.28 at 02:23:11 PM CDT 
//


package gameObjects;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.MutableTreeNode;

import coreGame.Game;
import gameData.ActionData;
import gameData.LinkData;

import javax.swing.JComboBox;
import javax.swing.JLayeredPane;
import javax.swing.BoxLayout;

import java.awt.BorderLayout;

import javax.swing.JLabel;
import javax.swing.JTextArea;

import java.awt.FlowLayout;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingConstants;
import javax.swing.JTextField;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;

public class Link extends Action{

	protected  ActionData actionData;
	private JTextField textField;
    
	public ActionData getActionData(){
		return actionData;	
	}
	
	public Link(LinkData data){
	this.actionData = data;
	data.setLinkedGameObject(this);
	}
	//Default consturctor. 
	public Link(){
	}
	
    public void run() {

    	System.err.println("ERROR! action " + actionData.getNAME()+ " exicuted unimplemented run method");
    }


}
