//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 12:29:58 PM CDT 
//


package gameData;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import gameObjects.Action;


/**
 * <p>Java class for ActionData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="linkedGameObject" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="transition" type="{}TransitionData"/>
 *           &lt;element name="pythonScript" type="{}PythonScriptData"/>
 *           &lt;element name="choice" type="{}ChoiceData"/>
 *           &lt;element name="ifTrue" type="{}IfTrueData"/>
 *           &lt;element name="action" type="{}ActionData"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionData", propOrder = {
    "linkedGameObject",
    "transitionOrPythonScriptOrChoice"
})
@XmlSeeAlso({
    IfTrueData.class,
    ChoiceData.class,
    PythonScriptData.class,
    TransitionData.class
})
public class ActionData {

    @XmlElement(required = true, type = Object.class)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Action linkedGameObject;
    @XmlElements({
        @XmlElement(name = "transition", type = TransitionData.class),
        @XmlElement(name = "pythonScript", type = PythonScriptData.class),
        @XmlElement(name = "choice", type = ChoiceData.class),
        @XmlElement(name = "ifTrue", type = IfTrueData.class),
        @XmlElement(name = "action")
    })
    protected List<ActionData> transitionOrPythonScriptOrChoice;
    @XmlAttribute(name = "NAME")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String name;
    @XmlAttribute(name = "ref")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected ActionData ref;

    /**
     * Gets the value of the linkedGameObject property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Action getLinkedGameObject() {
        return linkedGameObject;
    }

    /**
     * Sets the value of the linkedGameObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLinkedGameObject(Action value) {
        this.linkedGameObject = value;
    }

    /**
     * Gets the value of the transitionOrPythonScriptOrChoice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transitionOrPythonScriptOrChoice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransitionOrPythonScriptOrChoice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransitionData }
     * {@link PythonScriptData }
     * {@link ChoiceData }
     * {@link IfTrueData }
     * {@link ActionData }
     * 
     * 
     */
    public List<ActionData> getTransitionOrPythonScriptOrChoice() {
        if (transitionOrPythonScriptOrChoice == null) {
            transitionOrPythonScriptOrChoice = new ArrayList<ActionData>();
        }
        return this.transitionOrPythonScriptOrChoice;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public ActionData getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRef(ActionData value) {
        this.ref = value;
    }

}
