//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.13 at 10:02:40 PM EDT 
//


package gameData;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IfTrueData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IfTrueData">
 *   &lt;complexContent>
 *     &lt;extension base="{}ActionData">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="transition" type="{}TransitionData"/>
 *           &lt;element name="pythonScript" type="{}PythonScriptData"/>
 *           &lt;element name="choice" type="{}ChoiceData"/>
 *           &lt;element name="ifTrue" type="{}IfTrueData"/>
 *           &lt;element name="action" type="{}ActionData"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="py" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IfTrueData", propOrder = {
    "transitionOrPythonScriptOrChoice"
})
public class IfTrueData
    extends ActionData
{

    @XmlElements({
        @XmlElement(name = "transition", type = TransitionData.class),
        @XmlElement(name = "pythonScript", type = PythonScriptData.class),
        @XmlElement(name = "choice", type = ChoiceData.class),
        @XmlElement(name = "ifTrue", type = IfTrueData.class),
        @XmlElement(name = "action")
    })
    protected List<ActionData> transitionOrPythonScriptOrChoice;
    @XmlAttribute(name = "py")
    protected String py;

    /**
     * Gets the value of the transitionOrPythonScriptOrChoice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transitionOrPythonScriptOrChoice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransitionOrPythonScriptOrChoice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransitionData }
     * {@link PythonScriptData }
     * {@link ChoiceData }
     * {@link IfTrueData }
     * {@link ActionData }
     * 
     * 
     */
    public List<ActionData> getTransitionOrPythonScriptOrChoice() {
        if (transitionOrPythonScriptOrChoice == null) {
            transitionOrPythonScriptOrChoice = new ArrayList<ActionData>();
        }
        return this.transitionOrPythonScriptOrChoice;
    }

    /**
     * Gets the value of the py property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPy() {
        return py;
    }

    /**
     * Sets the value of the py property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPy(String value) {
        this.py = value;
    }

}
