//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.25 at 02:30:40 PM EDT 
//


package gameData;


import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import coreGame.Game;


/**
 * <p>Java class for IfTrueData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IfTrueData">
 *   &lt;complexContent>
 *     &lt;extension base="{}ActionData">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="py" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IfTrueData")
public class IfTrue
    extends Action
{
	
	
	
	@Override
	public String toString() {
    	if(this.getNAME() == null){
    		return "IF: " + this.getPy();
    	}
		return "IF: " + this.getNAME();
	}
   
    public DefaultMutableTreeNode getNode(){
		DefaultMutableTreeNode node = new DefaultMutableTreeNode(this);
		for (Action actionData : this.getTransitionOrPythonScriptOrChoice()){
			node.add(actionData.getLinkedGameObject().getNode());
		}
	return node;
	}
    
	public void run() {
		if( Game.currentGame.pythonController.eval(this.getPy()).__nonzero__()){
		for (Action actionData : this.getTransitionOrPythonScriptOrChoice()) {
			actionData.getLinkedGameObject().run();
	}
		}}
	   /**
	    * @wbp.parser.entryPoint
	    */
	   @Override
	public void addEditorPannel(JPanel panel) {
		   super.addEditorPannel(panel);
			JPanel panel_1 = new JPanel();
	    	panel.add(panel_1);
		
	}

    @XmlAttribute(name = "py")
    protected String py;

    /**
     * Gets the value of the py property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPy() {
        return py;
    }

    /**
     * Sets the value of the py property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPy(String value) {
        this.py = value;
    }

}
