//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.25 at 03:40:24 PM CDT 
//


package GameData;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the GameData package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MainGameData_QNAME = new QName("", "mainGameData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: GameData
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MainGameData }
     * 
     */
    public MainGameData createMainGameData() {
        return new LoadedMainGameData();
    }

    /**
     * Create an instance of {@link Choice }
     * 
     */
    public Choice createChoice() {
        return new LoadedChoice();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new LoadedAction();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new LoadedState();
    }

    /**
     * Create an instance of {@link Transition }
     * 
     */
    public Transition createTransition() {
        return new LoadedTransition();
    }

    /**
     * Create an instance of {@link PythonScript }
     * 
     */
    public PythonScript createPythonScript() {
        return new LoadedPythonScript();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MainGameData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mainGameData")
    public JAXBElement<MainGameData> createMainGameData(MainGameData value) {
        return new JAXBElement<MainGameData>(_MainGameData_QNAME, ((Class) LoadedMainGameData.class), null, ((LoadedMainGameData) value));
    }

}
