//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.25 at 02:30:40 PM EDT 
//


package gameData;

import java.awt.FlowLayout;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import coreGame.Game;


/**
 * <p>Java class for StateData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StateData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="titleText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="transition" type="{}TransitionData"/>
 *           &lt;element name="ifTrue" type="{}IfTrueData"/>
 *           &lt;element name="pythonScript" type="{}PythonScriptData"/>
 *           &lt;element name="choice" type="{}ChoiceData"/>
 *           &lt;element name="action" type="{}ActionData"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StateData", propOrder = {
    "text",
    "titleText",
    "transitionOrIfTrueOrPythonScript"
})
public class State extends GameObject {


	  @XmlTransient private JTextField textField;


	public void addEditorPannel(JPanel panel) {
		
		panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		
		JPanel panel_1 = new JPanel();
		panel.add(panel_1);
		Vector<String> keySet = new Vector<String>();
		for (String s : Game.currentGame.actions.keySet()){
		keySet.add(s);
		}
		
		JPanel panel_2 = new JPanel();
		panel_1.add(panel_2);
		
		JLabel lblActionRef = new JLabel("NAME:");
		lblActionRef.setVerticalAlignment(SwingConstants.TOP);
		panel_2.add(lblActionRef);
		
		textField = new JTextField();
		textField.setColumns(20);
		textField.addFocusListener(new FocusAdapter() {
			@Override
			public void focusLost(FocusEvent e) {
				rename(textField.getText());
			}
		});
		panel_2.add(textField);
		//textField.setColumns(10);
	}
	
protected void rename(String text) {
		// TODO Auto-generated method stub
		
	}
@Override
	public String toString() {
    	if(this.getNAME() == null && this.getTitleText()!= null){
    		return this.getTitleText();
    	}
		return  this.getNAME();
 }

public void runActions() {
	for (Action actionData :  this.getTransitionOrIfTrueOrPythonScript()) {
		actionData.run();	
	}
}
	
	
	
    @XmlElement(required = true)
    protected String text;
    @XmlElement(required = true)
    protected String titleText;
    @XmlElements({
        @XmlElement(name = "transition", type = Transition.class),
        @XmlElement(name = "ifTrue", type = IfTrue.class),
        @XmlElement(name = "pythonScript", type = PythonScript.class),
        @XmlElement(name = "choice", type = Choice.class),
        @XmlElement(name = "action")
    })
    protected List<Action> transitionOrIfTrueOrPythonScript;
    @XmlAttribute(name = "NAME", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String name;

   
    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the titleText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleText() {
        return titleText;
    }

    /**
     * Sets the value of the titleText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleText(String value) {
        this.titleText = value;
    }

    /**
     * Gets the value of the transitionOrIfTrueOrPythonScript property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transitionOrIfTrueOrPythonScript property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransitionOrIfTrueOrPythonScript().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transition }
     * {@link IfTrue }
     * {@link PythonScript }
     * {@link Choice }
     * {@link ActionData }
     * 
     * 
     */
    public List<Action> getTransitionOrIfTrueOrPythonScript() {
        if (transitionOrIfTrueOrPythonScript == null) {
            transitionOrIfTrueOrPythonScript = new ArrayList<Action>();
        }
        return this.transitionOrIfTrueOrPythonScript;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

}
