//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.25 at 02:30:40 PM EDT 
//


package gameData;

import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import coreGame.Game;

import javax.swing.JPopupMenu;

import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.SpinnerListModel;
import javax.swing.JComboBox;
import java.awt.BorderLayout;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;


/**
 * <p>Java class for TransitionData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransitionData">
 *   &lt;complexContent>
 *     &lt;extension base="{}ActionData">
 *       &lt;sequence>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransitionData", propOrder = {
    "state"
})
public class Transition
    extends Action
{
	

@Override
public String toString() {
	if(this.getNAME() == null){
		return "Transition to: " + this.getState().toString();
	}
	return "Transition: " + this.getNAME();
}
public DefaultMutableTreeNode getNode(){
	DefaultMutableTreeNode node = new DefaultMutableTreeNode(this);
return node;
}

public void run() {
    
    Game.currentGame.gameWindow.goToState( this.getState());
}
/**
 * @wbp.parser.entryPoint
 */
@Override
public void addEditorPannel(JPanel panel) {
	super.addEditorPannel(panel);
	JPanel panel_1 = new JPanel();
	panel.add(panel_1);
	panel_1.setLayout(new BorderLayout(0, 0));
	
	JLabel lblSt = new JLabel("Target State:");
	panel_1.add(lblSt, BorderLayout.WEST);
	
	final JComboBox<State> comboBox = new JComboBox();
	comboBox.addFocusListener(new FocusAdapter() {
		@Override
		public void focusLost(FocusEvent e) {
			if (comboBox.getSelectedItem()!= null){
				setState((State)comboBox.getSelectedItem());
				
			}
		}
	});
	comboBox.setModel(new DefaultComboBoxModel(Game.currentGame.getAllStates().toArray()));
	comboBox.setSelectedItem(this.getState());
	panel_1.add(comboBox, BorderLayout.CENTER);
}

	
	
	
	
	

    @XmlElement(required = true, type = Object.class)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected State state;

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public State getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setState(State value) {
        this.state = value;
    }


}
